### ISSUE TITLE
提供半个美团买菜的脚本

### ISSUE THREAD

**Issue by pigeon2049** [sean529/robFood#3]
```
const to_mall_cart = () => {

	

	shopping_cart_btn=id('img_shopping_cart').findOne()
		
	if(shopping_cart_btn){
		shopping_cart_btn.parent().click() //btn上一级控件可点击
		toast('已进入购物车')
	}else{
		toast('未找到购物车按钮，退出')
		exit;
	}


	
}

const submit_order = (count) => {

		toast('抢菜第'+count+'次尝试')
		//美团买菜 结算按钮无id
		submit_btn=textStartsWith('结算').findOne()
		if(!submit_btn){
			toast('未找到结算按钮，退出')
			exit;
		}
		submit_btn.parent().click() //结算按钮点击

		sleep(1000)

		if(textStartsWith('我知道了').exists()){
			toast('配送运力已约满')
			textStartsWith('我知道了').findOne().parent().click()
		}

		sleep(100)
		count=count+1;
		if(count>200){
			toast('抢菜失败')
			exit;
		}
		submit_order(count)
}

const start = () => {

	const appName = "美团买菜";
	launchApp(appName);
	sleep(600);  
	auto.waitFor()
	//跳过开屏广告
	btn_skip=id('btn_skip').findOne()
	if(btn_skip){
		btn_skip.click()
		toast('已跳过开屏广告')
	}
	sleep(600);  
	//跳过后加载首页会有一段时间再加载出购物车

	to_mall_cart()
	sleep(3000) //等待购物车加载完成
	submit_order(0)
}
```

因为没有挤进结算页，所以结算页的逻辑得看看明天能不能早起调试了

**Comment by pigeon2049** [comment]
https://gist.github.com/zgl018/742b661edd2902e80db4bfca59d01e1a
提供完整脚本 需要手动改下kill_app的方式和自定义音乐提醒路径，不同手机不太一样

**Comment by Sean529** [comment]
👍🏻 优秀

**Comment by zhangwbnn** [comment]
> ```
> const to_mall_cart = () => {
> 
> 	
> 
> 	shopping_cart_btn=id('img_shopping_cart').findOne()
> 		
> 	if(shopping_cart_btn){
> 		shopping_cart_btn.parent().click() //btn上一级控件可点击
> 		toast('已进入购物车')
> 	}else{
> 		toast('未找到购物车按钮，退出')
> 		exit;
> 	}
> 
> 
> 	
> }
> 
> const submit_order = (count) => {
> 
> 		toast('抢菜第'+count+'次尝试')
> 		//美团买菜 结算按钮无id
> 		submit_btn=textStartsWith('结算').findOne()
> 		if(!submit_btn){
> 			toast('未找到结算按钮，退出')
> 			exit;
> 		}
> 		submit_btn.parent().click() //结算按钮点击
> 
> 		sleep(1000)
> 
> 		if(textStartsWith('我知道了').exists()){
> 			toast('配送运力已约满')
> 			textStartsWith('我知道了').findOne().parent().click()
> 		}
> 
> 		sleep(100)
> 		count=count+1;
> 		if(count>200){
> 			toast('抢菜失败')
> 			exit;
> 		}
> 		submit_order(count)
> }
> 
> const start = () => {
> 
> 	const appName = "美团买菜";
> 	launchApp(appName);
> 	sleep(600);  
> 	auto.waitFor()
> 	//跳过开屏广告
> 	btn_skip=id('btn_skip').findOne()
> 	if(btn_skip){
> 		btn_skip.click()
> 		toast('已跳过开屏广告')
> 	}
> 	sleep(600);  
> 	//跳过后加载首页会有一段时间再加载出购物车
> 
> 	to_mall_cart()
> 	sleep(3000) //等待购物车加载完成
> 	submit_order(0)
> }
> ```
> 
> 因为没有挤进结算页，所以结算页的逻辑得看看明天能不能早起调试了

今天可以吗，新版本好像失败情况比较多

**Comment by Cyberman-Dalek** [comment]
> https://gist.github.com/zgl018/742b661edd2902e80db4bfca59d01e1a
> 
> 提供完整脚本 需要手动改下kill_app的方式和自定义音乐提醒路径，不同手机不太一样

大佬成功了吗，会有封号的风险吗

**Comment by yueql** [comment]
无敌卷王

**Comment by pigeon2049** [comment]
> https://gist.github.com/zgl018/742b661edd2902e80db4bfca59d01e1a 提供完整脚本 需要手动改下kill_app的方式和自定义音乐提醒路径，不同手机不太一样


可能会有其它未抢到的情况 v 友们自行添加,以及忘记加的一行 start()

给个饿不死的思路：
外卖平台药店是正常的，建议下单葡萄糖粉剂 500g+维生素矿物质软糖
理论上一天摄入 60g 葡萄糖就可以维生了

**Comment by lonelystone545** [comment]
> > https://gist.github.com/zgl018/742b661edd2902e80db4bfca59d01e1a 提供完整脚本 需要手动改下kill_app的方式和自定义音乐提醒路径，不同手机不太一样
> 
> 可能会有其它未抢到的情况 v 友们自行添加,以及忘记加的一行 start()
> 
> 给个饿不死的思路： 外卖平台药店是正常的，建议下单葡萄糖粉剂 500g+维生素矿物质软糖 理论上一天摄入 60g 葡萄糖就可以维生了

这个脚本怎么运行额？可以出个详细版本的教程么

**Comment by sheyor** [comment]
> https://gist.github.com/zgl018/742b661edd2902e80db4bfca59d01e1a 提供完整脚本 需要手动改下kill_app的方式和自定义音乐提醒路径，不同手机不太一样
请问一下魅族手机的kill_app方式应该怎么改，我运行后出来的就是强制退出的界面
